### ISSUE TITLE
TED-Ed does not scrape anymore

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#148]
https://farm.openzim.org/recipes/teded_en_all stops after a few seconds with the following error:
```
Attempting to update youtube-dl…
Requirement already satisfied: youtube-dl in /usr/local/lib/python3.8/site-packages (2021.6.6)
[youtube2zim::2021-06-27 06:15:08,912] INFO:starting youtube scraper for channel#UCsooa4yRKGN_zEE8iknghZA
[youtube2zim::2021-06-27 06:15:08,912] INFO:preparing build folder at /output/tmps0l0gviu
[youtube2zim::2021-06-27 06:15:08,972] INFO:testing Youtube credentials
[youtube2zim::2021-06-27 06:15:09,264] INFO:testing S3 Optimization Cache credentials
[youtube2zim::2021-06-27 06:15:11,623] INFO:checking your branding files and values
[youtube2zim::2021-06-27 06:15:11,623] INFO:compute playlists list to retrieve
[youtube2zim::2021-06-27 06:15:11,624] DEBUG:query youtube-api for Channel #UCsooa4yRKGN_zEE8iknghZA
[youtube2zim::2021-06-27 06:15:11,710] DEBUG:query youtube-api for Playlists of channel #UCsooa4yRKGN_zEE8iknghZA
[youtube2zim::2021-06-27 06:15:12,060] DEBUG:query youtube-api for Playlist #PLJicmE8fK0EithsL37nZumzo_Ox5r4RCc
[youtube2zim::2021-06-27 06:15:12,139] DEBUG:query youtube-api for Playlist #PLJicmE8fK0Ej1VitSjiQCHSvbpqg73Lnc
[youtube2zim::2021-06-27 06:15:12,214] DEBUG:query youtube-api for Playlist #PLJicmE8fK0EhMjOWNNhlY4Lxg8tupXKhC
[youtube2zim::2021-06-27 06:15:12,293] ERROR:FAILED. An error occurred: 'channelId'
[youtube2zim::2021-06-27 06:15:12,293] ERROR:'channelId'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.14-py3.8.egg/youtube2zim/entrypoint.py", line 202, in main
    scraper.run()
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.14-py3.8.egg/youtube2zim/scraper.py", line 266, in run
    self.extract_playlists()
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.14-py3.8.egg/youtube2zim/scraper.py", line 459, in extract_playlists
    ) = extract_playlists_details_from(self.collection_type, self.youtube_id)
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.14-py3.8.egg/youtube2zim/youtube.py", line 328, in extract_playlists_details_from
    [Playlist.from_id(playlist_id) for playlist_id in list(set(playlist_ids))],
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.14-py3.8.egg/youtube2zim/youtube.py", line 328, in <listcomp>
    [Playlist.from_id(playlist_id) for playlist_id in list(set(playlist_ids))],
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.14-py3.8.egg/youtube2zim/youtube.py", line 41, in from_id
    creator_id=playlist_json["snippet"]["channelId"],
KeyError: 'channelId'
```
Maybe the same like #138

**Comment by rgaudin** [comment]
Looks similar to #138

**Comment by kelson42** [comment]
@rgaudin It seems to work again, maybe Minfield would work as well again?
