### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe' 

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#156]
https://farm.openzim.org/pipeline/d9ba00d0a26b4df419eb4e26/debug

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 22.2.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/local/bin/youtube2zim", line 33, in <module>
    sys.exit(load_entry_point('youtube2zim==2.1.14.dev0', 'console_scripts', 'youtube2zim')())
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.14.dev0-py3.8.egg/youtube2zim/__main__.py", line 13, in main
    from youtube2zim.entrypoint import main as entry
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.14.dev0-py3.8.egg/youtube2zim/entrypoint.py", line 9, in <module>
    from .scraper import Youtube2Zim
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.14.dev0-py3.8.egg/youtube2zim/scraper.py", line 23, in <module>
    import jinja2
  File "/usr/local/lib/python3.8/site-packages/Jinja2-2.11.3-py3.8.egg/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.8/site-packages/Jinja2-2.11.3-py3.8.egg/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.8/site-packages/Jinja2-2.11.3-py3.8.egg/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/Jinja2-2.11.3-py3.8.egg/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/site-packages/MarkupSafe-2.1.1-py3.8-linux-x86_64.egg/markupsafe/__init__.py)

**Comment by rgaudin** [comment]
Fixed via 59998c7
