### ISSUE TITLE
KeyError: 'items'

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#160]
[youtube2zim::2022-08-05 18:56:14,308] INFO:compute playlists list to retrieve
[youtube2zim::2022-08-05 18:56:14,309] DEBUG:query youtube-api for Channel #dirtybiology
[youtube2zim::2022-08-05 18:56:14,513] ERROR:Invalid channelId `dirtybiology`: Not Found
[youtube2zim::2022-08-05 18:56:14,514] ERROR:FAILED. An error occurred: 'items'
[youtube2zim::2022-08-05 18:56:14,514] ERROR:'items'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.17-py3.8.egg/youtube2zim/entrypoint.py", line 202, in main
    scraper.run()
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.17-py3.8.egg/youtube2zim/scraper.py", line 267, in run
    self.extract_playlists()
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.17-py3.8.egg/youtube2zim/scraper.py", line 463, in extract_playlists
    ) = extract_playlists_details_from(self.collection_type, self.youtube_id)
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.17-py3.8.egg/youtube2zim/youtube.py", line 312, in extract_playlists_details_from
    channel_json = get_channel_json(youtube_id)
  File "/usr/local/lib/python3.8/site-packages/youtube2zim-2.1.17-py3.8.egg/youtube2zim/youtube.py", line 88, in get_channel_json
    channel_json = req.json()["items"][0]
KeyError: 'items'

From https://farm.openzim.org/pipeline/b29b002ba3ee7c3a1776de26/debug

**Comment by rgaudin** [comment]
As you can see in your extract above: `ERROR:Invalid channelId dirtybiology: Not Found` the channel with this name is not found. Given https://www.youtube.com/channel/dirtybiology returns a 404, I suppose the channel has either been removed or suspended. I disabled the recipe on zimfarm.
