### ISSUE TITLE
Crash with "crashcourse"

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#17]
```
youtube2zim https://www.youtube.com/user/crashcourse eng Kiwix --lowquality
```
...

```
[download] Downloading video 712 of 712
[youtube] FrlJl2UXRU0: Downloading webpage
[youtube] FrlJl2UXRU0: Downloading video info webpage
[youtube] FrlJl2UXRU0: Extracting video information
[youtube] FrlJl2UXRU0: Downloading MPD manifest
[youtube] FrlJl2UXRU0: Downloading MPD manifest
[download] Finished downloading playlist: Uploads from CrashCourse
Rendering template...
Traceback (most recent call last):
  File "/media/kelson/SOTOKI/venv/bin/youtube2zim", line 11, in <module>
    sys.exit(run())
  File "/media/kelson/SOTOKI/venv/local/lib/python2.7/site-packages/youtube/youtube2zim.py", line 489, in run
    videos=write_video_info(sorted_list,parametre,scraper_dir,background_color,videos)
  File "/media/kelson/SOTOKI/venv/local/lib/python2.7/site-packages/youtube/youtube2zim.py", line 171, in write_video_info
    subtitles = download_video_thumbnail_subtitles(id, item.get('subtitles'), title_clean)
TypeError: download_video_thumbnail_subtitles() takes exactly 4 arguments (3 given)

```

**Comment by dattaz** [comment]
correct on 604c456928458381c236ae9ff330853d05dd3667 yesterday
