### ISSUE TITLE
Skin of colors can not be scraped anymore

### ISSUE THREAD

**Issue by kelson42** [openzim/youtube#66]
```

FAILED. An error occured: save() argument after ** must be a mapping, not NoneType save() argument after ** must be a mapping, not NoneType Traceback (most recent call last):   File "/usr/local/lib/python3.6/dist-packages/youtube2zim-2.1.0-py3.6.egg/youtube2zim/entrypoint.py", line 178, in main     scraper.run()   File "/usr/local/lib/python3.6/dist-packages/youtube2zim-2.1.0-py3.6.egg/youtube2zim/scraper.py", line 250, in run     self.check_branding_values()   File "/usr/local/lib/python3.6/dist-packages/youtube2zim-2.1.0-py3.6.egg/youtube2zim/scraper.py", line 367, in check_branding_values     resize_image(self.profile_path, width=100, height=100, method="thumbnail")   File "/usr/local/lib/python3.6/dist-packages/youtube2zim-2.1.0-py3.6.egg/youtube2zim/utils.py", line 105, in resize_image     str(to) if to is not None else fpath, image.format, **kwargs.get(image.format) TypeError: save() argument after ** must be a mapping, not NoneType
--

```

**Comment by rgaudin** [comment]
recipe is 2.1.0 instead of 2.1.1. I believe this is fixed.

**Comment by kelson42** [comment]
@rgaudin I have updated all recipes
