### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by nabinkhadka** [openzim/youtube#77]
On mac osx (python3), I am getting the following error:

```
(testenv) nabin@khadka Downloads % youtube2zim
Traceback (most recent call last):
  File "/Users/nabin/Downloads/testenv/bin/youtube2zim", line 8, in <module>
    sys.exit(main())
  File "/Users/nabin/Downloads/testenv/lib/python3.7/site-packages/youtube2zim/__main__.py", line 13, in main
    from youtube2zim.entrypoint import main as entry
  File "/Users/nabin/Downloads/testenv/lib/python3.7/site-packages/youtube2zim/entrypoint.py", line 9, in <module>
    from .scraper import Youtube2Zim
  File "/Users/nabin/Downloads/testenv/lib/python3.7/site-packages/youtube2zim/scraper.py", line 42, in <module>
    from .converter import post_process_video
  File "<fstring>", line 1
    (video_format=)
```

#bug

**Comment by rgaudin** [comment]
P3 version not supported: probably < 3.6 as it doesn't support f-strings. Use 3.8 as advertised in setup.py
